### ISSUE TITLE
Run on CI (Gitlab CI example)

### ISSUE THREAD

**Issue by vindarel** [vindarel/colisper#1]
We currently have to use my fork of the script. Awaiting get.comby.dev to be updated (https://github.com/comby-tools/comby/issues/228).

Example .gitlab-ci.yaml:

```
image: daewok/lisp-devel

stages:
  - test 
  - build

before_script:
  - apt-get update -qy
  - apt-get install -y git-core

qa:
  allow_failure: true
  stage: test
  script:
    # QA tools:
    # install Comby:
    - apt-get install -y sudo
    - adduser lisp sudo
    # - bash <(curl -sL get.comby.dev)
    - bash <(curl -sL https://raw.githubusercontent.com/vindarel/comby/set-release-1.0.0/scripts/install.sh)
    # install Colisper:
    - git clone https://github.com/vindarel/colisper ~/colisper
    - chmod +x ~/colisper/colisper.sh
    # run it on my source files:
    - cd src/ && ~/colisper/colisper.sh
```

Result:

![Selection_146](https://user-images.githubusercontent.com/3721004/104613092-29fdba80-5687-11eb-9a0d-e222115e41dc.png)
